### ISSUE TITLE
uh

### ISSUE THREAD

**Issue by michszhu** [michzzzm/teams#5]
tPHP Fatal error:  Uncaught Google_Service_Exception: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"1\" at 'data.values[20]': Cannot find field.\nInvalid JSON payload received. Unknown name \"2\" at 'data.values[20]': Cannot find field.",
    "errors": [
      {
        "message": "Invalid JSON payload received. Unknown name \"1\" at 'data.values[20]': Cannot find field.\nInvalid JSON payload received. Unknown name \"2\" at 'data.values[20]': Cannot find field.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
 in C:\Users\jiang\vendor\google\apiclient\src\Google\Http\REST.php:118
Stack trace:
#0 C:\Users\jiang\vendor\google\apiclient\src\Google\Http\REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 C:\Users\jiang\vendor\google\apiclient\src\Google\Task\Runner.php(181): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), O in C:\Users\jiang\vendor\google\apiclient\src\Google\Http\REST.php on line 118

**Comment by michszhu** [comment]
adding events to people with only one event
